README.rst

Python modules Cython and Packaging are needed to install the PDAL Python extension, it seems useful to list them as requirements with an example of how to install them

Added python dependencies

---

setup.py

`PDALVERSION` is not set in the clean target.

Don't append library in clean target.

---

setup.py

`PDALVERSION` is not set when executing `setup.py clean`.
Ref: #24 
This fixes the Debian package build where the clean target is executed first outside the build chroot where pdal is not installed.

Fix clean target.

---

pdal/pio.py
test/test_pio.py

Thought I'd see if this kind interface would be of interest.  In the same spirit as #21, this is a module that allows pipelines to be constructed a bit more easily in python, without using an explicit vocabulary.  Constructing a pipeline using this module looks like this:
```Python
from pdal import pio
pipeline = (pio.readers.ply(filename="dummyinput.ply") +
pio.filters.outlier(method="statistical", mean_k=16, multiplier=1.0) +
pio.filters.range(limits="Classification![7:7]") +
pio.filters.normal() + pio.writers.ply(storage_mode="ascii", precision=4, filename="dummyoutput.ply",
dims="X,Y,Z,Red,Green,Blue,NormalX,NormalY,NormalZ"))
```
To execute a pipeline and return the numpy structured array.  I've been parsing this into an [Open3D](https://github.com/intel-isl/Open3D) point cloud but …

Pythonic pipeline construction sugar proposal?

---

pdal/libpdalpython.pyx
test/test_pipeline.py

This code from https://github.com/PDAL/python/blob/3d94698d789f6dcb498a2cb127c06e49d1cd89e1/pdal/PyPipeline.cpp#L169
```python
for (auto i: pvset)
{
//ABELL - Leak?
Array *array = new python::Array;
array->update(i);
output.push_back(array);
}
```
allocates an array for each `pvset` but the arrays were were never released. This PR Fixes this  by releasing the memory of the c++ arrays used to pass the data to the python binding.
Closes #23

Fix memory leak

---

CMakeLists.txt
test/test_pypy.py

This fixes https://github.com/PDAL/python/issues/75

Allow using "filters.python" in a python process on OS X

---

.gitignore
PKG-INFO
README.rst
pdal/CMakeLists.txt
pdal/PyMesh.cpp
pdal/PyMesh.hpp
pdal/PyPipeline.cpp
pdal/libpdalpython.pyx
pdal/pipeline.py
test/data/mesh.json
test/test_pipeline.py

Adds the ability to access face data from meshes in the Python API:
- Adds a new method to `pdal.Pipeline` called `get_meshes()` that returns a list of `ndarray` in the same format as `get_arrays()`. Each `ndarray` represents one mesh from one `PointView`and is a (1, size) array of Triangles, where each triangle is a tuple of `(index of corner a, index of corner b, index of corner c)` - the index referring to the points in `PointView` array.
- Adds the details to `libpdalpython.pyx` to implement the above,
- Adds a method to the cpp `Pipeline` class called `getMeshes()` that returns a vector of PyMesh
- Adds a cpp class `PyMesh` very much a copy of the `PyArray` class, in this case the class creates the mesh ndarray.
All of the above is working on my builds and does not introduce any new …

Add Meshes to the pdal API

---

pdal/plang/Environment.cpp
pdal/plang/Invocation.cpp
pdal/test/PythonFilterTest.cpp
test/test_pipeline.py

I have changes to the doc in the PDAL repo.
Close #87

Use out_metadata for output metadata

---

README.rst
pdal/CMakeLists.txt
pdal/PyPipeline.cpp
pdal/PyPipeline.hpp
pdal/StreamableExecutor.cpp
pdal/StreamableExecutor.hpp
pdal/__init__.py
pdal/libpdalpython.pyx
pdal/pipeline.py
test/data/range.json
test/data/range.py
test/test_pipeline.py

Alternative implementation of #90 using a separate thread to execute the pipeline in streaming mode in the background, with minimal changes to PDAL core. Thanks to @abellgithub for the idea and the [initial implementation](https://github.com/PDAL/python/commit/c383e79704b54558bffa6ce51da5f60752a486fa).
This PR is built on top of #91. ~It also requires https://github.com/PDAL/PDAL/pull/3567; there is a [temporary commit](https://github.com/PDAL/python/commit/9d9439482cdb437ea67896d47cb489eaa3736ab4) for running the CI (Python 3.8 only) against a custom PDAL build that uses the aforementioned PR.~

Pipeline iterator - parallelized version

---

CHANGES.txt
README.rst
pdal/__init__.py

Prepare for next major release. Also update the README pipeline example to use a TileDB writer stage.

Release v3.0.0

---

pdal/PyPipeline.cpp
pdal/PyPipeline.hpp
pdal/libpdalpython.cpp
test/test_pipeline.py

Many readers support QuickInfo for fetching stuff about a data source without executing a pipeline. This is quite useful for asking information from COPC and LAS files, for example.

implement QuickInfo support

---

pdal/PyPipeline.cpp
pdal/pipeline.py
test/test_pipeline.py

This changes a behavior of the base library throwing when you ask for a pipeline if it hadn't been executed. That was really a consequence of the old design and is no longer needed.
This patch is needed for convenient Dask operations.

add pickling support for Pipeline

---

pdal/drivers.py
pdal/libpdalpython.cpp
setup.py

#107 was not correct. This implementation moves driver options to the c++ library instead of shelling out to `pdal` commands.

Proper fix of #107, driver option fetching.

---

pdal/StreamableExecutor.hpp
pdal/libpdalpython.cpp
test/test_pipeline.py

* Make pipeline.metadata return an object instead of string
* Make pipeline.quickinfo return an object instead of a string
* Add iterator.metadata to return PointTable metadata

Interface updates

---

.github/workflows/build.yml
pdal/__init__.py
pdal/libpdalpython.cpp
test/test_pipeline.py

PDAL's metadata can spit non-utf8 characters into its JSON output. This patch will ignore them, and we'll also patch PDAL to not spit out utf-8 in its JSON going forward at 2.5.0+
This should fix https://github.com/PDAL/PDAL/issues/3880 once released.

harden getMetadata and related calls from getting non-utf-8 'json' 

---

pdal/libpdalpython.cpp

* `executeStream` already does GIL release
* pybind11 does GIL acquisition with each call, we don't need to be doing that everywhere

Cleanup GIL stuff

---

.github/workflows/build.yml
CMakeLists.txt
pyproject.toml
src/pdal/PyArray.cpp
src/pdal/PyArray.hpp
src/pdal/PyPipeline.cpp
src/pdal/PyPipeline.hpp
src/pdal/StreamableExecutor.cpp
src/pdal/__main__.py
src/pdal/libpdalpython.cpp

This was tested against Numpy 2.0rc1 as well and the tests were successful.

Set Numpy floor to 1.22 and NPY_NO_DEPRECATED_API NPY_1_22_API_VERSION

---

.github/environment.yml
src/pdal/pipeline.py
test/test_pipeline.py

GeoDataFrame support added for if GeoPandas is available.
GeoPandas import mirrors existing Pandas import.
Pipeline.get_geodataframe method added. Users can get an array from an executed pipeline as a GeoDataFrame instead of a Pandas DataFrame. Optional arguments included for specifying XY vs XYZ point geometries and for providing CRS information to the GeoDataFrame constructor.
Pipeline(dataframes) modified so that columns named "geometry" will be dropped before conversion to structured arrays.

Add GeoDataFrame support to Pipeline

---

src/pdal/PyArray.cpp
src/pdal/PyArray.hpp
src/pdal/PyPipeline.cpp
src/pdal/PyPipeline.hpp
src/pdal/StreamableExecutor.cpp
src/pdal/StreamableExecutor.hpp
src/pdal/libpdalpython.cpp
test/test_pipeline.py

This PR implements support for filtering the allowed dimensions used by pipelines in `execute` and `executeStreaming`. See the test for inspiration how to use it.

Support limiting dimensions with execute() and executeStreaming()

---

README.rst
src/pdal/PyArray.cpp
src/pdal/PyArray.hpp
src/pdal/PyPipeline.cpp
src/pdal/libpdalpython.cpp
src/pdal/pipeline.py
test/test_pipeline.py

I've faced a couple of cases where I wasn't able to fit all my input data in memory to then run a (streamed) PDAL pipeline with it.
With these changes, you'd be able to stream the input data into the Pipeline. This has helped me:
* To relieve memory requirements from certain pipelines
* Enable the streaming of data provided by libraries that support it (ex: [pye57](https://github.com/davidcaron/pye57) or pdal itself)
See below a very simple example of usage just for illustrative purposes.
<details>
<summary>
Streaming the read and write of a very large LAZ file. <br/>
With support for tweaking both input and output chunk sizes
</summary>
```python
import numpy as np
import pdal
def run():
in_chunk_size = 10_000_000
in_pipeline = pdal.Reader.las(**{
"filename": "in_test.laz"
}).pipeline() …
```

Adding support for streaming through the input arrays of a pipeline
